# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='access',
        ),
        migrations.AddField(
            model_name='role',
            name='access',
            field=models.ManyToManyField(to='errand.Access'),
        ),
    ]
