# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0002_auto_20160220_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Emplyoee'), ('3', 'Errand Boy')], max_length=50),
        ),
    ]
