# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0003_auto_20160220_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Emplyoee', 'Emplyoee'), ('Errand Boy', 'Errand Boy')], max_length=50),
        ),
    ]
