# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0006_auto_20160220_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('Errand Boy', 'Errand Boy')], max_length=50),
        ),
    ]
